export const AUTHENTICATED = 'authenticated_user'
export const UNAUTHENTICATED = 'unauthenticated_user'
export const AUTHENTICATION_ERROR = 'authentication_error'
export const SIGNUP_LOADING = 'signup_loading'
export const SIGNUP_SUCCESS = 'signup_success'
export const SIGNUP_ERROR = 'signup_error'
